all: comm_progs

comm_progs:
	g++ -o contenful.o contenful.cpp -lcurl

# docker run -it --rm -v C:\dev\cursostec\estructuras:/home gcc bash
# cd /cygdrive/c/Users/isasc/Documents/Caso#5/socket/
# ./contenful.o

# cd /cygdrive/c/Users/isasc/Documents/Caso#5/
# g++ -o Caso#5.o Caso#5.cpp -lcurl
# g++ -o pruebas.o pruebas.cpp -lcurl
# ./Caso#5.o